name: 6pillars.ai IaC Security Scan
description: "Run 6pillars.ai IaC security scan on pull requests"
author: "6pillars"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "shield"
  color: "orange"

inputs:
  timeoutSeconds:
    description: "Time in seconds to wait for testing to complete before initiating a timeout of the action."
    default: 1200
  complianceCopilotUrl:
    description: "Compliance Copilot Url"
    default: "https://api.app.6pillars.ai"
  excludeFolder:
    description: "Skip folders from being processed"
    default: .github
  folderPath :
    description: "Specify a folder path to process"
    default: ""
  skipPullRequestComments :
    description: "Skip comments in Pull Request"
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.timeoutSeconds }}
    - ${{ inputs.complianceCopilotUrl }}
    - ${{ inputs.excludeFolder }}
    - ${{ inputs.folderPath }}
    - ${{ inputs.skipPullRequestComments }}
