name: 6pillars Compliance Copilot Action
description: "Run 6pillars.ai Compliance Copilot to detect AWS IaC misconfigurations in your pull requests"
author: "6pillars"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "shield"
  color: "orange"

inputs:
  timeoutSeconds:
    description: "Time in seconds to wait for testing to complete before initiating a timeout of the action."
    default: 1200
  complianceCopilotUrl:
    description: "Compliance Copilot Url"
    default: "https://api.app.6pillars.ai"
  excludeFolder:
    description: "Skip folders from being processed"
    default: .github
  folderPath :
    description: "Specify a folder path to process"
    default: ""
  skipPullRequestComments :
    type: boolean
    description: "Skip comments in Pull Request"
    default: false
  minimumSeverity:
    type: choice
    description: "Minimum severity level to fail the check"
    required: true
    default: CRITICAL
    options: 
    - CRITICAL
    - HIGH
    - MEDIUM
    - LOW
    - NONE
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.timeoutSeconds }}
    - ${{ inputs.complianceCopilotUrl }}
    - ${{ inputs.excludeFolder }}
    - ${{ inputs.folderPath }}
    - ${{ inputs.skipPullRequestComments }}
    - ${{ inputs.minimumSeverity }}
